[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "thash"
description = 'A very compact representation of an image placeholder (thumbhash, RGBA-safe fork)'
readme = "README.md"
requires-python = ">=3.7"
license = "MIT"
keywords = ["thumbhash", "placeholder", "image", "hash"]
authors = [
  { name = "Jianqi Pan", email = "jannchie@gmail.com" },
  { name = "Justin Forlenza", email = "justin@forlenza.co" },
]
classifiers = [
  "Development Status :: 5 - Production/Stable",
  "Programming Language :: Python",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Programming Language :: Python :: 3.9",
  "Programming Language :: Python :: 3.10",
  "Programming Language :: Python :: 3.11",
  "Programming Language :: Python :: 3.12",
  "Programming Language :: Python :: Implementation :: CPython",
  "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
]
dynamic = ["version"]

[project.optional-dependencies]
pillow = [
  "pillow"
]

[project.urls]
Documentation = "https://github.com/Jannchie/thumbhash-py#readme"
Issues = "https://github.com/Jannchie/thumbhash-py/issues"
Source = "https://github.com/Jannchie/thumbhash-py"

[tool.hatch.version]
path = "thash/__about__.py"

[tool.hatch.build.targets.wheel]
packages = ["thash"]

[tool.hatch.build.targets.sdist]
include = ["thash", "README.md", "LICENSE"]

[tool.hatch.envs.default]
dependencies = [
  "pytest",
  "pytest-cov",
]
[tool.hatch.envs.default.scripts]
cov = "pytest --cov-report=term-missing --cov-config=pyproject.toml --cov=thash --cov=tests {args}"
no-cov = "cov --no-cov {args}"

[[tool.hatch.envs.test.matrix]]
python = ["37", "38", "39", "310", "311", "312"]

[tool.coverage.run]
branch = true
parallel = true
omit = [
  "thash/__about__.py",
]

[tool.coverage.report]
exclude_lines = [
  "no cov",
  "if __name__ == .__main__.:",
  "if TYPE_CHECKING:",
]
